/*
 * *
 *  * Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 */

// Generated by scripts/generate-web-public-api.mjs.
export { COMMAND_CATEGORIES, COMMANDS } from '../config/command-registry';
export type { CommandCategory, CommandDefinition } from '../config/command-registry';
export { QUICK_ACTIONS } from '../config/quick-actions';
export type { ExpertCardConfig, QuickActionConfig } from '../config/quick-actions';
export { SHORTCUTS } from '../config/shortcut-registry';
export type { ShortcutDefinition } from '../config/shortcut-registry';
