/*
 * *
 *  * Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 */

// Generated by scripts/generate-web-public-api.mjs.
export { USER_THEME_OPTIONS } from '../constants/userThemeOptions';
export type { UserThemeOption } from '../constants/userThemeOptions';
