/*
 * *
 *  * Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 */

// Generated by scripts/generate-web-public-api.mjs.
export { APIG_DAILY_QUOTA_EXHAUSTED_ERROR_CODE, getAgentErrorToastContent, getDailyQuotaExhaustedChatMessage, getFriendlyAgentErrorMessage, getRateLimitChatMessage, getSensitiveInputErrorToastContent, isDailyQuotaExhaustedAgentError, isRateLimitError, isSensitiveInputAgentError, MODEL_ARTS_RATE_LIMIT_ERROR_CODE, MODEL_ARTS_SENSITIVE_INPUT_ERROR_CODE } from '../hooks/agent-error-fallback';
export type { ErrorLike } from '../hooks/agent-error-fallback';
export { parseSystemInfoContent } from '../hooks/parse-system-info';
export { isSchedulerPlaceholderMessage } from '../hooks/scheduler-placeholder';
export { requestThreadLiveRefresh, THREAD_LIVE_REFRESH_EVENT } from '../hooks/thread-live-refresh';
export type { ThreadLiveRefreshDetail, ThreadLiveRefreshScope } from '../hooks/thread-live-refresh';
export { _resetAgentDataCache, formatAgentName, getCachedAgents, useAgentData } from '../hooks/useAgentData';
export type { AgentData } from '../hooks/useAgentData';
export { useAgentMessages } from '../hooks/useAgentMessages';
export { useAskUserQuestion } from '../hooks/useAskUserQuestion';
export { useAuthorization } from '../hooks/useAuthorization';
export type { AuthPendingRequest, RespondScope } from '../hooks/useAuthorization';
export { useAvailableClients } from '../hooks/useAvailableClients';
export type { AvailableClient, UiHints } from '../hooks/useAvailableClients';
export { isCommandInvocation, useChatCommands } from '../hooks/useChatCommands';
export { useChatHistory } from '../hooks/useChatHistory';
export { useChatSocketCallbacks } from '../hooks/useChatSocketCallbacks';
export { primeCoCreatorConfigCache, resetCoCreatorConfigCacheForTest, useCoCreatorConfig } from '../hooks/useCoCreatorConfig';
export { useCountUp } from '../hooks/useCountUp';
export { useCountdown } from '../hooks/useCountdown';
export { useDesktopWindowControls } from '../hooks/useDesktopWindowControls';
export type { DesktopResizeDirection } from '../hooks/useDesktopWindowControls';
export { useElapsedTime } from '../hooks/useElapsedTime';
export { useEscapeKey } from '../hooks/useEscapeKey';
export type { UseEscapeKeyOptions } from '../hooks/useEscapeKey';
export { _resetExpertCatalogCache, expertToAgentData, getCachedExperts, useExpertCatalog } from '../hooks/useExpertCatalog';
export type { ExpertCatalogItem } from '../hooks/useExpertCatalog';
export { useFeatureDocDetail } from '../hooks/useFeatureDocDetail';
export { useFilePicker } from '../hooks/useFilePicker';
export { useInspirationTemplate } from '../hooks/useInspirationTemplate';
export type { InspirationTemplateState } from '../hooks/useInspirationTemplate';
export { useMessageFeedback } from '../hooks/useMessageFeedback';
export type { MessageFeedbackState, MessageFeedbackVote } from '../hooks/useMessageFeedback';
export { usePathCompletion } from '../hooks/usePathCompletion';
export type { PathEntry } from '../hooks/usePathCompletion';
export { usePersistedState } from '../hooks/usePersistedState';
export { usePlaceholderFileUpload } from '../hooks/usePlaceholderFileUpload';
export { usePreventSleep } from '../hooks/usePreventSleep';
export { getFileTypeIcon, usePromptBlocks } from '../hooks/usePromptBlocks';
export { usePushNotify } from '../hooks/usePushNotify';
export type { PushDeliverySummary, PushStatusPayload, UsePushNotifyReturn } from '../hooks/usePushNotify';
export { useSendMessage } from '../hooks/useSendMessage';
export type { MentionRef, SendMessageOptions, UploadStatus, UseSendMessageOptions, WhisperOptions } from '../hooks/useSendMessage';
export { consumeBackgroundSystemInfo } from '../hooks/useSocket-background-system-info';
export { clearBackgroundStreamRefForActiveEvent, handleBackgroundAgentMessage } from '../hooks/useSocket-background';
export type { ActiveRoutedAgentMessage, BackgroundAgentMessage, BackgroundStoreLike, BackgroundStreamRef, BackgroundToastInput, HandleBackgroundMessageOptions } from '../hooks/useSocket-background';
export { loadJoinedRoomsFromSession, saveJoinedRoomsToSession } from '../hooks/useSocket-persistence';
export { useSocket } from '../hooks/useSocket';
export type { SocketCallbacks } from '../hooks/useSocket';
export { useSplitPaneKeys } from '../hooks/useSplitPaneKeys';
export { useStreamingAudio } from '../hooks/useStreamingAudio';
export { useTheme } from '../hooks/useTheme';
export type { ThemeType } from '../hooks/useTheme';
export { useTts } from '../hooks/useTts';
export type { TtsState, UseTtsReturn } from '../hooks/useTts';
export { handleVadSpeechStart, useVadInterrupt } from '../hooks/useVadInterrupt';
export type { VadState } from '../hooks/useVadInterrupt';
export { useVoiceAutoPlay } from '../hooks/useVoiceAutoPlay';
export { useVoiceInput } from '../hooks/useVoiceInput';
export type { VoiceState } from '../hooks/useVoiceInput';
export { getPlaybackManager, handleVoiceChunk, handleVoiceStreamEnd, handleVoiceStreamStart, useVoiceStream } from '../hooks/useVoiceStream';
