/*
 * *
 *  * Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 */

// Generated by scripts/generate-web-public-api.mjs.
export { bubbleExpandStorageKey, readBubbleExpandPref, writeBubbleExpandPref } from '../lib/chat-bubble-expand-prefs';
export { hexToRgba, tintedLight } from '../lib/color-utils';
export { getMentionColor, getMentionLabel, getMentionRe, getMentionToAgentId, refreshCoCreatorMentionData, refreshMentionData, refreshThreadExpertMentionData, resetMentionDataForTest } from '../lib/mention-highlight';
export { buildNameInitialIconDataUrl, getNameInitial, getNameInitialIconTheme } from '../lib/name-initial-icon';
export type { NameInitialIconTheme } from '../lib/name-initial-icon';
export { parseDirection } from '../lib/parse-direction';
export type { DirectionInfo } from '../lib/parse-direction';
export { buildThinkingExecutionLabel, countAssistantToolUses, formatThinkingDurationHuman, resolveThinkingExecutionDurationMs } from '../lib/thinking-execution-label';
