/*
 * *
 *  * Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 */

// Generated by scripts/generate-web-public-api.mjs.
export { MAIN_PANEL_MIN_WIDTH } from '../shared/constants';
