/*
 * *
 *  * Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 */

// Generated by scripts/generate-web-public-api.mjs.
export { normalizeAgentSaveErrorMessage } from '../utils/agent-save-error';
export { API_URL, apiFetch } from '../utils/api-client';
export type { ApiFetchOptions } from '../utils/api-client';
export { readBuildEnv, readPublicEnv } from '../utils/client-env';
export { compressImage } from '../utils/compressImage';
export { notifyOnTaskComplete, notifyToolApprovalRequest, requestNotificationPermission, showBrowserNotification } from '../utils/desktop-notification';
export type { DesktopNotificationOptions, ToolApprovalNotificationOptions } from '../utils/desktop-notification';
export { compareMessagesByOrder, getMessageOrderValue, resolveAssistantMessageTimestamp } from '../utils/message-order';
export type { ResolveAssistantMessageTimestampInput } from '../utils/message-order';
export { buildFinalPrompt, getPlaceholderDefaultText } from '../utils/promptBuilder';
export type { FinalPromptResult } from '../utils/promptBuilder';
export { parsePromptTemplate, resetPlaceholderCounter } from '../utils/promptParser';
export type { FilePlaceholder, FixedBlock, ParsedPrompt, PlaceholderBlock, PromptBlock, TextPlaceholder } from '../utils/promptParser';
export { downloadBlob, downloadProtectedResource, fetchProtectedResource, fetchProtectedResourceBlob, isProtectedResourceUrl } from '../utils/protected-resource';
export { DEFAULT_DEDUPE_WINDOW_MS, isPushTestNotificationTag, LEGACY_DECISION_TAG_PREFIX, OFFICE_DECISION_TAG_PREFIX, PUSH_TEST_NOTIFICATION_TAG, resetPushTestNotification, shouldDedupeNotification, shouldForceSystemNotification, shouldShowSystemNotification, shouldSuppressDuplicateNotification } from '../utils/push-notification-policy';
export type { NotificationDedupeRegistry, NotificationRegistry, PushNotificationPayload } from '../utils/push-notification-policy';
export { buildQueueInlineSegments } from '../utils/queue-inline-segments';
export type { QueueInlineSegment, QueueInlineToken } from '../utils/queue-inline-segments';
export { computeScrollRecomputeSignal } from '../utils/scrollRecomputeSignal';
export { scrollToMessage } from '../utils/scrollToMessage';
export { fetchSkillOptionsWithCache, getCachedSkillOptions, invalidateSkillOptionsCache, notifySkillOptionsChanged, seedSkillOptionsCache, SKILL_OPTIONS_UPDATED_EVENT } from '../utils/skill-options-cache';
export type { SkillOption } from '../utils/skill-options-cache';
export { skillSourceToLabel } from '../utils/skill-source-label';
export type { SkillSource } from '../utils/skill-source-label';
export { buildContinueMessage } from '../utils/taskProgressContinue';
export { buildThemeBootstrapScript, DEFAULT_THEME, persistTheme, readThemeFromBrowserCookie, readThemeFromBrowserStorage, readThemeFromCookieString, readThemeFromDocument, resolvePersistedTheme, THEME_STORAGE_KEY } from '../utils/theme-persistence';
export type { ThemeType } from '../utils/theme-persistence';
export { exportThreadImage, exportThreadText } from '../utils/thread-export';
export type { ThreadExportTextFormat } from '../utils/thread-export';
export { compactToolResultDetail } from '../utils/toolPreview';
export { applyTermDictionary, correctTranscription, mergeTermEntries, normalizeSpeechMentions, refreshSpeechAliases, removeFillers } from '../utils/transcription-corrector';
export type { TermEntry } from '../utils/transcription-corrector';
export { base64ToBlob, streamTts } from '../utils/tts-stream';
export { clearAuthIdentity, getCanCreateModel, getDomainId, getIsSkipAuth, getUserId, getUserName, setAuthIdentity, setCanCreateModel, setIsSkipAuth, setUserId, setUserName } from '../utils/userId';
